### ISSUE TITLE
Contrast difference for agenda tasks that are overdue and scheduled today

### ISSUE THREAD

**Issue by novoid** [rougier/nano-emacs#134]
Hi,

After using a couple of themes, I'm currently testing nano emacs not only for reasons of color, as you might guess. One thing that is a downer to me is that AFAIR all other themes did have a different contrast setting of tasks that are overdue and scheduled today on my agenda.

As a bad habbit, I collect many overdue tasks on my agenda. They are usually with a lower contrast color theme.

Tasks that are scheduled for today (I'm not using deadlines at the moment) do come with a higher contrast, which makes them easier to spot in a long agenda list.

My proposal: Maybe you want to add support for the latter as my current nano-emacs agenda does not seem to use higher contrast colors for the text (not the keywords which do have a fine contrast) of the tasks that are scheduled for the current day.

Thanks!

I'm using c313957 from 3 weeks ago.

**Comment by rougier** [comment]
Would have some suggestions (and possibly screenshots) to see the changes?
By the way, tou might also consider nano-theme (on ELPA) that provides the same color theme but is easier to customize.

**Comment by novoid** [comment]
Sure.

Here is my current Emacs nano setup of my agenda (blurred):

![2023-01-16T18 16 49 Emacs nano agenda -- screenshots anonymized](https://user-images.githubusercontent.com/727493/212735734-e993386d-7b45-4b2a-8a0a-d6ce94cbf888.png)

The very same view in my previously used [wombat theme](https://github.com/emacs-mirror/emacs/blob/master/etc/themes/wombat-theme.el).

![2023-01-16T18 19 37 Emacs wombat theme -- screenshots anonymized](https://user-images.githubusercontent.com/727493/212735738-5c72c9e2-3910-49a6-a5e8-b7ba7be988f8.png)

As you can see, the wombat themed org-super-agenda is using the clearly distinguishable green color for items that are due/scheduled this very day. The overdue items (the majority) are using orange and red colors.

With the nano theme, all items do use the identical font color for today's items and overdue items. This is much harder to parse by the human eye in order to find out today's tasks in contrast to overdue tasks from previous days.

I haven't looked into nano-theme yet but I will consider it. Do you - by chance - know that there is a pre-defined different setting for today's tasks and overdue tasks in the other nano theme?

Thanks!

**Comment by rougier** [comment]
Sorry for delay. Here is the part for org-agenda in nano-theme:

```
   '(org-agenda-calendar-event      ((t (:inherit nano-default))))
   '(org-agenda-calendar-sexp       ((t (:inherit nano-salient))))
   '(org-agenda-clocking            ((t (:inherit nano-faded))))
   '(org-agenda-column-dateline     ((t (:inherit nano-faded))))
   '(org-agenda-current-time        ((t (:inherit (nano-strong
                                                   nano-salient)))))
   '(org-agenda-date                ((t (:inherit nano-strong))))
   '(org-agenda-date-today          ((t (:inherit (nano-salient
                                                   nano-strong)))))
   '(org-agenda-date-weekend        ((t (:inherit nano-faded))))
   '(org-agenda-diary               ((t (:inherit nano-faded))))
   '(org-agenda-dimmed-todo-face    ((t (:inherit nano-faded))))
   '(org-agenda-done                ((t (:inherit nano-faded))))
   '(org-agenda-filter-category     ((t (:inherit nano-faded))))
   '(org-agenda-filter-effort       ((t (:inherit nano-faded))))
   '(org-agenda-filter-regexp       ((t (:inherit nano-faded))))
   '(org-agenda-filter-tags         ((t (:inherit nano-faded))))
   '(org-agenda-property-face       ((t (:inherit nano-faded))))
   '(org-agenda-restriction-lock    ((t (:inherit nano-faded))))
   '(org-agenda-structure           ((t (:inherit nano-strong))))
```

Which one corresponds to your case ?

**Comment by novoid** [comment]
Good question. I don't know the details about this.

Main goal is to have a clearly different face for overdue items (scheduled/deadline yesterday or older) in contrast to items scheduled/deadline for today.

**Comment by rougier** [comment]
Can you check the face for overdue items in your agenda (using `describe-face` when the point is on an overdue item)

**Comment by novoid** [comment]
> Can you check the face for overdue items in your agenda (using `describe-face` when the point is on an overdue item)

Perfect. Thanks for the pointer.

`describe-face` asks me for something and I use the default "hl-line".

Okay, here we go: scheduled today:
```
           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: #3B4252
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
           Extend: t
          Inherit: highlight
```

For an item that is overdue it's the same.

I guess this is something you weren't hoping for. I guess that's related to some of [my settings](https://github.com/novoid/dot-emacs/blob/master/config.org):
```
  (add-hook 'org-agenda-mode-hook '(lambda () (hl-line-mode 1)))
```
... this might interfere with nano-emacs I guess. I don't know because this should only change the settings of the current agenda line AFAIK.

**Comment by rougier** [comment]
You need first to disable hl-line mode and then describe-face should describe face under point.

**Comment by novoid** [comment]
Of course. So, I disabled hl-line-mode and rebootet Emacs.

`describe-face` now has the default `org-scheduled-today` when invoked over an item which is scheduled for today:

```
Documentation:
Face for items scheduled for a certain day.

Defined in  org-faces.el .


           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: unspecified
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
           Extend: unspecified
          Inherit: nano-face-faded
```

The overdue item has `org-scheduled-previously` and looks the same in its output.
