### ISSUE TITLE
Question about customization

### ISSUE THREAD

**Issue by Ieremies** [rougier/nano-emacs#90]
Hello, and first of all, I love nano and all the great work you put out!
I'm a doom user and was trying to put together nano with doom. I got it, for the most part, but I can figure out what is this line at the bottom.
![image](https://user-images.githubusercontent.com/36969625/126081400-26029c2c-6f6c-45ca-8afe-56b6d8a8ec62.png)
It is supposed to be the dashed line. I know it's not a nano issue, but i would appreciate some guidance as to where to look, I don't even know the name of the line.
Thanks!

**Comment by Ieremies** [comment]
Update: it only occurs when I use the client for my emacs daemon. When I use create another process, not based on the daemon, it stays as I want it.

**Comment by rougier** [comment]
This line is actually the modeline with a tiny font (size = 0.1) and a black overline. Does that answer your question?

**Comment by Ieremies** [comment]
It actually does because now I can search for this modeline face and see the reason why this black line is that, for some reason, it has an underline:
```
Face: mode-line (sample) (customize this face)

Documentation:
Basic mode line face for selected window.

Defined in ‘faces.el’.


           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: 0.1
           Weight: unspecified
            Slant: unspecified
       Foreground: #37474F
DistantForeground: unspecified
       Background: #FFFFFF
        Underline: t
         Overline: nil
   Strike-through: unspecified
              Box: nil
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
           Extend: unspecified
          Inherit: unspecified

```
Will try to find where does it come from. Thanks!
